theme: minima
minima:
  skin: auto
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/sukeya" }
    - { platform: twitter, user_url: "https://twitter.com/ReZeroRemLover" }

title: 私の愛した数式
description: 物理シミュレーションや数学に関するブログです。

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag

github: [metadata]

permalink: /:year/:month/:day/:title

lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
